# Generated by Django 4.1.7 on 2023-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_confirmusercode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmusercode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
